### ISSUE TITLE
Obnoxious "Slow Down!" Popup

### ISSUE THREAD

**Issue by KaydaCant** [Alphatism/DeathLink#1]
![image](https://github.com/Alphalaneous/DeathLink/assets/97423855/55c03d20-1e3e-4f4e-8945-99a5a507d379)
This popup appears constantly and consistently around every 10 deaths and it makes playing levels with other people extremely annoying, especially when using DeathLink with a large group as most of our time is spent re-linking to eachother. This happens no matter how long each attempt is and makes actually beating levels together nearly impossible without constantly worrying about being kicked off the network. Maybe change it so some sort of deaths per unit of time or something instead of strictly every 10 deaths to make sure the network isn't overloaded, while not being super obnoxious to people using it normally?

**Comment by Alphalaneous** [comment]
This sounds more like a bug because server side it is supposed to be deaths/second, I’ll look into fixing it.

**Comment by KaydaCant** [comment]
Seems to be fixed server side, closing this for now.
